In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,roc_auc_score,classification_report,f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler 

In [2]:
df = pd.read_csv('./dane/HeartDiseaseDataSet.csv') 
df.head()

age     sex                cp  trestbps   chol                    fbs  \
0  63.0    male    typical angina     145.0  233.0  greater than 120mg/ml   
1  67.0    male      asymptomatic     160.0  286.0    lower than 120mg/ml   
2  67.0    male      asymptomatic     120.0  229.0    lower than 120mg/ml   
3  37.0    male  non-anginal pain     130.0  250.0    lower than 120mg/ml   
4  41.0  female   atypical angina     130.0  204.0    lower than 120mg/ml   

                        restecg  thalach exang  oldpeak        slope   ca  \
0  left ventricular hypertrophy    150.0    no      2.3  downsloping  0.0   
1  left ventricular hypertrophy    108.0   yes      1.5         flat  3.0   
2  left ventricular hypertrophy    129.0   yes      2.6         flat  2.0   
3                        normal    187.0    no      3.5  downsloping  0.0   
4  left ventricular hypertrophy    172.0    no      1.4    upsloping  0.0   

                thal  target  
0       fixed defect       0  
1             normal       1  
2  reversable defect       1  
3             normal       0  
4             normal       0

In [3]:
df_dummies = pd.get_dummies(data=df,drop_first=True)
df_dummies.head()

age  trestbps   chol  thalach  oldpeak   ca  target  sex_male  \
0  63.0     145.0  233.0    150.0      2.3  0.0       0         1   
1  67.0     160.0  286.0    108.0      1.5  3.0       1         1   
2  67.0     120.0  229.0    129.0      2.6  2.0       1         1   
3  37.0     130.0  250.0    187.0      3.5  0.0       0         1   
4  41.0     130.0  204.0    172.0      1.4  0.0       0         0   

   cp_atypical angina  cp_non-anginal pain  cp_typical angina  \
0                   0                    0                  1   
1                   0                    0                  0   
2                   0                    0                  0   
3                   0                    1                  0   
4                   1                    0                  0   

   fbs_lower than 120mg/ml  restecg_left ventricular hypertrophy  \
0                        0                                     1   
1                        1                                     1   
2                        1                                     1   
3                        1                                     0   
4                        1                                     1   

   restecg_normal  exang_yes  slope_flat  slope_upsloping  thal_normal  \
0               0          0           0                0            0   
1               0          1           1                0            1   
2               0          1           1                0            0   
3               1          0           0                0            1   
4               0          0           0                1            1   

   thal_reversable defect  
0                       0  
1                       0  
2                       1  
3                       0  
4                       0

In [4]:
df_dummies.shape

(297, 19)

In [5]:
num_cols=['age','trestbps','chol','thalach','oldpeak','ca']

In [6]:
y = df_dummies["target"]
X = df_dummies.drop('target',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 0)

scaler = StandardScaler()
X_train.loc[:,num_cols] = scaler.fit_transform(X_train.loc[:,num_cols])

X_test.loc[:,num_cols] = scaler.transform(X_test.loc[:, num_cols])


D:\ToolsP\Anaconda\envs\hdenv\lib\site-packages\pandas\core\indexing.py:1734: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())
D:\ToolsP\Anaconda\envs\hdenv\lib\site-packages\pandas\core\indexing.py:1734: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())


In [7]:
X_train

age  trestbps      chol   thalach   oldpeak        ca  sex_male  \
282  0.400423  2.009219 -0.446639 -0.157767  1.541875  1.410869         0   
81  -0.144981 -0.161919  0.314335 -0.288963 -0.559775 -0.712153         0   
108 -1.672110 -0.813261 -0.563712 -0.420159  0.140775 -0.712153         1   
146 -1.453948 -1.138932  0.041165  1.285388 -0.910050 -0.712153         1   
217 -1.453948 -1.138932  0.392384  0.979264 -0.910050 -0.712153         0   
..        ...       ...       ...       ...       ...       ...       ...   
251 -1.235787 -0.976096  1.075310  1.372852  0.140775 -0.712153         1   
192  1.382149 -1.790273  0.997261 -1.076139 -0.121931  1.410869         1   
117  0.945826 -0.161919  1.602138 -0.770015  0.666188  2.472380         1   
47  -0.472223  0.923650 -0.095420 -0.944943  1.366738 -0.712153         1   
172  1.054907  0.652258 -0.700297 -0.770015  0.841325  1.410869         1   

     cp_atypical angina  cp_non-anginal pain  cp_typical angina  \
282                   0                    0                  0   
81                    0                    0                  0   
108                   0                    0                  0   
146                   0                    1                  0   
217                   0                    1                  0   
..                  ...                  ...                ...   
251                   0                    0                  0   
192                   0                    0                  0   
117                   0                    0                  0   
47                    0                    0                  0   
172                   0                    0                  0   

     fbs_lower than 120mg/ml  restecg_left ventricular hypertrophy  \
282                        0                                     1   
81                         1                                     1   
108                        1                                     0   
146                        1                                     0   
217                        1                                     1   
..                       ...                                   ...   
251                        1                                     0   
192                        1                                     1   
117                        0                                     1   
47                         1                                     1   
172                        1                                     1   

     restecg_normal  exang_yes  slope_flat  slope_upsloping  thal_normal  \
282               0          1           1                0            0   
81                0          0           1                0            1   
108               1          0           1                0            0   
146               1          0           0                1            1   
217               0          1           0                1            1   
..              ...        ...         ...              ...          ...   
251               1          0           1                0            1   
192               0          1           1                0            1   
117               0          1           0                1            0   
47                0          0           1                0            0   
172               0          0           1                0            0   

     thal_reversable defect  
282                       0  
81                        0  
108                       1  
146                       0  
217                       0  
..                      ...  
251                       0  
192                       0  
117                       1  
47                        1  
172                       0  

[237 rows x 18 columns]

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
y_pred_lr = classifier.predict(X_test)

lr_acc_score=metrics.accuracy_score(y_test, y_pred_lr)
print('Test Accuracy score: ', lr_acc_score)
lr_conf_matrix = confusion_matrix(y_test, y_pred_lr)
print("confusion matrix")
print(lr_conf_matrix)

Test Accuracy score:  0.8333333333333334
confusion matrix
[[28  2]
 [ 8 22]]


In [74]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred_dt = classifier.predict(X_test)

dt_acc_score=metrics.accuracy_score(y_test, y_pred_dt)
print('Test Accuracy score: ', dt_acc_score)
dt_conf_matrix = confusion_matrix(y_test, y_pred_dt)
print("confusion matrix")
print(dt_conf_matrix)

Test Accuracy score:  0.6833333333333333
confusion matrix
[[21  9]
 [10 20]]


In [27]:
knn = KNeighborsClassifier(metric='manhattan', n_neighbors=3)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
knn_acc_score=metrics.accuracy_score(y_test, y_pred_knn)
print(f'{knn.score(X_test,y_test)}')
print('Test Accuracy score: ', knn_acc_score)
knn_conf_matrix = confusion_matrix(y_test, y_pred_knn)
print("confusion matrix")
print(knn_conf_matrix)

0.8
Test Accuracy score:  0.8
confusion matrix
[[26  4]
 [ 8 22]]


> - czułość | tp/tp+fn| = 27/30 = .9
> - precyzja | tp/ tp+fp | = 27/36 = 0,75

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

acc_score=metrics.accuracy_score(y_test, y_pred)
print('Test Accuracy score: ', acc_score)
conf_matrix = confusion_matrix(y_test, y_pred_knn)
print("confusion matrix")
print(conf_matrix)

Test Accuracy score:  0.8
confusion matrix
[[28  2]
 [10 20]]


In [12]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw.color

0      red
1    green
2     blue
3    green
4      red
Name: color, dtype: object

In [13]:
df_raw['size'].value_counts()

M     2
L     2
XL    1
Name: size, dtype: int64

In [14]:
pd.get_dummies(data=df_raw)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0     500       0       0        1           0            0          1   
1   89.0     450       1       0        0           0            1          0   
2   99.0     300       0       1        0           1            0          0   
3  129.0     380       1       0        0           0            1          0   
4   79.0     410       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

In [15]:
data2 = pd.get_dummies(data=df_raw,drop_first=True)

In [16]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        5 non-null      float64
 1   weight       5 non-null      int64  
 2   size_M       5 non-null      uint8  
 3   size_XL      5 non-null      uint8  
 4   color_green  5 non-null      uint8  
 5   color_red    5 non-null      uint8  
 6   gender_male  5 non-null      uint8  
 7   bought_yes   5 non-null      uint8  
dtypes: float64(1), int64(1), uint8(6)
memory usage: 238.0 bytes


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       297 non-null    float64
 1   sex       297 non-null    object 
 2   cp        297 non-null    object 
 3   trestbps  297 non-null    float64
 4   chol      297 non-null    float64
 5   fbs       297 non-null    object 
 6   restecg   297 non-null    object 
 7   thalach   297 non-null    float64
 8   exang     297 non-null    object 
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    object 
 11  ca        297 non-null    float64
 12  thal      297 non-null    object 
 13  target    297 non-null    int64  
dtypes: float64(6), int64(1), object(7)
memory usage: 32.6+ KB
